name: Pre-commit auto-update

on:
  workflow_dispatch:

jobs:
  update-pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Update dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
          pre-commit autoupdate

      - name: Create pull request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Update pre-commit dependencies
          labels: cleanup-no-release-required, dependencies, github_actions
          title: Update pre-commit dependencies
